jobs:
- job: "CallGithubWorkflow"
  pool:
    vmImage: 'ubuntu-latest'

# NAME OF THE JOB THAT DEPENDS
  dependsOn:
  - HyperLinkValidations
  - SolutionValidations
  - JsonFileValidation
  - KqlValidations
  - logoValidator
  - NonAsciiValidations
  - PlaybooksValidations
  - sampleDataValidator
  - WorkbooksTemplateValidations
  - WorkbooksValidations
  - ContentValidations
  - DataConnectorValidations
  - DetectionsValidations
  - DetectionTemplateSchemaValidation
  - DocumentsLinkValidation
  - YamlFileValidation

  condition: |
    and
    (
      ne(variables['SYSTEM.PULLREQUEST.ISFORK'], 'true'),
      ne(variables['Build.SourceBranch'], 'refs/heads/master'),
      ne(variables['System.PullRequest.SourceBranch'], 'master'),
      eq(variables['System.PullRequest.TargetBranch'], 'master'),
      eq(dependencies.HyperLinkValidations.result, 'Succeeded'),
      eq(dependencies.SolutionValidations.result, 'Succeeded'),
      eq(dependencies.JsonFileValidation.result, 'Succeeded'),
      eq(dependencies.KqlValidations.result, 'Succeeded'),
      eq(dependencies.logoValidator.result, 'Succeeded'),
      eq(dependencies.NonAsciiValidations.result, 'Succeeded'),
      eq(dependencies.PlaybooksValidations.result, 'Succeeded'),
      eq(dependencies.sampleDataValidator.result, 'Succeeded'),
      eq(dependencies.WorkbooksTemplateValidations.result, 'Succeeded'),
      eq(dependencies.WorkbooksValidations.result, 'Succeeded'),
      eq(dependencies.ContentValidations.result, 'Succeeded'),
      eq(dependencies.DataConnectorValidations.result, 'Succeeded'),
      eq(dependencies.DetectionsValidations.result, 'Succeeded'),
      eq(dependencies.DetectionTemplateSchemaValidation.result, 'Succeeded'),
      eq(dependencies.DocumentsLinkValidation.result, 'Succeeded'),
      eq(dependencies.YamlFileValidation.result, 'Succeeded')
    )
  steps:
  - pwsh: |
      try
      {
        $branchName = "$(System.PullRequest.SourceBranch)"
        $targetBranch = "$(System.PullRequest.TargetBranch)"
        $pullRequestNumber = "$(System.PullRequest.PullRequestNumber)"
        $isAutoGeneratedPR = [bool]($branchName -match "-automated-pr")
        Write-Host "BranchName is $branchName, pullRequestNumber $pullRequestNumber, isAutoGeneratedPR $isAutoGeneratedPR"

        # NOT MAIN/MASTER OR AUTOMATED BRANCH
        if ($branchName -ne 'master' -and $isAutoGeneratedPR -eq $false -and $targetBranch -eq 'master')
        {
          .script/package-automation/invokeGithubWorklow.ps1 $branchName $pullRequestNumber
        }
        else
        {
          Write-Host "Skipping Github Workflow from execution as current branch is a Master branch or is a automated PR or target branch is not master."
        }
      }
      catch
      {
        Write-Host "Error occured in callGithubWorkflow $_"
      }
    displayName: 'Call Github Workflow'
    env:
      GITHUB_TOKEN_VALUE: $(githubTokenValue)
    continueOnError: true