name: Pull Request Comment

on:  
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      prNumber:
        required: false
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@29423367f079522048aa7c63f671593b0556ffd5
        with:
          script: |
            $message = "${{ inputs.message }}"
            $prNumber = "${{ inputs.prNumber }}"
            console.log('message ' + $message + ', prNumber ' + $prNumber)
            $prNumber = $prNumber ? $prNumber : context.issue.number

            github.rest.issues.createComment({
              issue_number: $prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: $message
            })
