# ADD P0 LABEL IF THE PULL REQUEST IS FROM EXTERNAL PUBLISHER I.E ISV'S
name: "Pull Request Labeler"

on:  
  pull_request:
    branches:
      - master
    paths:
      - Solutions/**

jobs:
  solutionNameDetails:
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork && !contains(github.event.pull_request.labels.*.name, 'P0')}}
    uses: ./.github/workflows/getSolutionName.yaml
    secrets: inherit

  solutionPublisherDetail:
    needs: solutionNameDetails
    if: ${{ github.actor != 'dependabot[bot]' && needs.solutionNameDetails.outputs.solutionName != '' && !github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/neworexistingsolution.yaml
    with: 
      solutionName: "${{ needs.solutionNameDetails.outputs.solutionName }}"
    secrets: inherit

  Labeler:
    runs-on: ubuntu-latest
    needs: solutionPublisherDetail
    if: ${{ github.actor != 'dependabot[bot]' && needs.solutionPublisherDetail.outputs.solutionPublisherId != '' && !contains(fromJson(vars.INTERNAL_PUBLISHERS),needs.solutionPublisherDetail.outputs.solutionPublisherId) }}
    steps:
      - name: Add Label Notification
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['P0']
            })
            
